name: GitHub-Profile-Summary-Cards

on:
  schedule: # Ejecuta cada 24 horas
    - cron: "0 0 * * *"
  workflow_dispatch: # Permite ejecución manual

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-cards
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.SUMMARY_CARDS_TOKEN }}
        with:
          USERNAME: Natanael-1a2b
          BRANCH_NAME: main
          UTC_OFFSET: -4
          EXCLUDE: ""
          AUTO_PUSH: true
